In [1]:
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings('ignore')

In [2]:
df=sns.load_dataset('mpg')

In [3]:
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

In [4]:
df.head(10)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
5,15.0,8,429.0,198.0,4341,10.0,70,usa,ford galaxie 500
6,14.0,8,454.0,220.0,4354,9.0,70,usa,chevrolet impala
7,14.0,8,440.0,215.0,4312,8.5,70,usa,plymouth fury iii
8,14.0,8,455.0,225.0,4425,10.0,70,usa,pontiac catalina
9,15.0,8,390.0,190.0,3850,8.5,70,usa,amc ambassador dpl

In [5]:
df.drop('name',axis=1,inplace=True)

In [6]:
df.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

In [7]:
df.fillna(df.horsepower.median(),inplace=True)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,18.0,8,307.0,130.0,3504,12.0,70,usa
1,15.0,8,350.0,165.0,3693,11.5,70,usa
2,18.0,8,318.0,150.0,3436,11.0,70,usa
3,16.0,8,304.0,150.0,3433,12.0,70,usa
4,17.0,8,302.0,140.0,3449,10.5,70,usa
...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa
394,44.0,4,97.0,52.0,2130,24.6,82,europe
395,32.0,4,135.0,84.0,2295,11.6,82,usa
396,28.0,4,120.0,79.0,2625,18.6,82,usa
397,31.0,4,119.0,82.0,2720,19.4,82,usa

In [8]:
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

In [9]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower      float64
weight            int64
acceleration    float64
model_year        int64
origin              str
dtype: object

In [10]:
df.origin.value_counts

<bound method IndexOpsMixin.value_counts of 0         usa
1         usa
2         usa
3         usa
4         usa
        ...
393       usa
394    europe
395       usa
396       usa
397       usa
Name: origin, Length: 398, dtype: str>

In [11]:
df['origin']=df['origin'].map({'usa':1,'japan':2,'europe':3})
df['origin']=df['origin'].astype(int)

In [12]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower      float64
weight            int64
acceleration    float64
model_year        int64
origin            int64
dtype: object

In [14]:
X=df.drop('mpg',axis=1)

In [15]:
y=df['mpg']

In [16]:
X

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,8,307.0,130.0,3504,12.0,70,1
1,8,350.0,165.0,3693,11.5,70,1
2,8,318.0,150.0,3436,11.0,70,1
3,8,304.0,150.0,3433,12.0,70,1
4,8,302.0,140.0,3449,10.5,70,1
...,...,...,...,...,...,...,...
393,4,140.0,86.0,2790,15.6,82,1
394,4,97.0,52.0,2130,24.6,82,3
395,4,135.0,84.0,2295,11.6,82,1
396,4,120.0,79.0,2625,18.6,82,1
397,4,119.0,82.0,2720,19.4,82,1

In [17]:
y

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
 X_train, X_test, y_train, y_test =train_test_split(X,y,test_size=0.3,random_state=1)

In [20]:
from sklearn.linear_model import LinearRegression

In [21]:
regression_model=LinearRegression()

In [22]:
regression_model

LinearRegression()

In [23]:
regression_model.fit(X_train,y_train)

LinearRegression()

In [25]:
X_train.columns

Index(['cylinders', 'displacement', 'horsepower', 'weight', 'acceleration',
       'model_year', 'origin'],
      dtype='str')

In [26]:
for i,col_name in enumerate(X_train.columns):
        print(f"the coffecient of{col_name} is {regression_model.coef_[i]}")

the coffecient ofcylinders is -0.3176142302799283
the coffecient ofdisplacement is 0.026237482599078907
the coffecient ofhorsepower is -0.018270764913124578
the coffecient ofweight is -0.007487750398361905
the coffecient ofacceleration is 0.05040673461971364
the coffecient ofmodel_year is 0.8470951427061364
the coffecient oforigin is 1.5190958387975044

In [28]:
y_pred=regression_model.predict(X_test)

In [31]:
from sklearn.metrics import r2_score
r2_sc=r2_score(y_test,y_pred)
print(f"the variance score is{r2_sc}")

the variance score is0.8348001123742286

In [34]:
from sklearn.linear_model import Ridge
redge_regression_model=Ridge(alpha=0.1)
redge_regression_model.fit(X_train,y_train)

for i,col_name in enumerate(X_train.columns):
        print(f"the coffecient for {col_name} redge_regresion_model {redge_regression_model.coef_[i]}")

the coffecient for cylinders redge_regresion_model -0.3170032101006624
the coffecient for displacement redge_regresion_model 0.026213249757983056
the coffecient for horsepower redge_regresion_model -0.018263252481448927
the coffecient for weight redge_regresion_model -0.007487326050213115
the coffecient for acceleration redge_regresion_model 0.050368969474426165
the coffecient for model_year redge_regresion_model 0.8470062938903143
the coffecient for origin redge_regresion_model 1.5174528285653794

In [35]:
y_pred=redge_regression_model.predict(X_test)
from sklearn.metrics import r2_score
r2_sc=r2_score(y_test,y_pred)
print(f"the variance score is{r2_sc}")

the variance score is0.8348084889168358

In [36]:
from sklearn.linear_model import Lasso
lasso_regression_model=Lasso(alpha=0.5)
lasso_regression_model.fit(X_train,y_train)

Lasso(alpha=0.5)

In [37]:
for i,col_name in enumerate(X_train.columns):
        print(f"the coffecient for {col_name} redge_regresion_model {lasso_regression_model.coef_[i]}")

the coffecient for cylinders redge_regresion_model -0.0
the coffecient for displacement redge_regresion_model 0.0062081988883003186
the coffecient for horsepower redge_regresion_model -0.01105838298716961
the coffecient for weight redge_regresion_model -0.006982673168023082
the coffecient for acceleration redge_regresion_model 0.0
the coffecient for model_year redge_regresion_model 0.7446549520038186
the coffecient for origin redge_regresion_model 0.0

In [38]:
y_pred=lasso_regression_model.predict(X_test)
r2_sc=r2_score(y_test,y_pred)
print(f"the r square score is {r2_sc}")

the r square score is 0.8277934716635555

In [39]:
#lasso is use for feature selecting

In [43]:
from sklearn.linear_model import ElasticNet
elastic_regression_model=ElasticNet(alpha=1,l1_ratio=0.5) 
#(1-l1_ratio=l2_ratio)

In [44]:
elastic_regression_model.fit(X_train,y_train)

ElasticNet(alpha=1)

In [47]:
for i,col_name in enumerate(X_train.columns):
        print(f"the coffecient for {col_name} redge_regresion_model {elastic_regression_model.coef_[i]}")

the coffecient for cylinders redge_regresion_model -0.0
the coffecient for displacement redge_regresion_model 0.0058888699536675
the coffecient for horsepower redge_regresion_model -0.012403874933570147
the coffecient for weight redge_regresion_model -0.006934550516257623
the coffecient for acceleration redge_regresion_model 0.0
the coffecient for model_year redge_regresion_model 0.7133150744603869
the coffecient for origin redge_regresion_model 0.0

In [48]:
y_pred=elastic_regression_model.predict(X_test)
r2_sc=r2_score(y_test,y_pred)
print(f"the r square score is {r2_sc}")

the r square score is 0.8284840073256804